---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiro
  labels:
    app: kiro
    version: "{{.Version}}"
    team: "{{.Team}}"
spec:
  replicas: {{ .Config "replicas" }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kiro
  template:
    metadata:
      labels:
        app: kiro
        version: "{{.Version}}"
        team: "{{.Team}}"
    spec:
      containers:
      - name: kiro
        image: "quay.io/fortnox/{{.ServiceName}}:{{.Version}}"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        envFrom:
        - configMapRef:
            name: kiro








